server:
  port: 8765

spring:
  application:
    name: gateway-service

zuul:
  sensitive-headers:
    - Cookie
    - Set-Cookie
  routes:
    login:
      path: /authors/login
      serviceId: authentication-service
      stripPrefix: false
    logout:
      path: /authors/logout
      serviceId: authentication-service
      stripPrefix: false
    validate:
      path: /authors/validate
      serviceId: authentication-service
      stripPrefix: false
    authors:
      path: /authors
      serviceId: registration-service
      stripPrefix: false
#    offices:
#      path: /offices/**
#      serviceId: user-service
#      stripPrefix: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka